from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Presentation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("tag_ru", models.CharField(max_length=80, verbose_name="Тег (RU)")),
                ("tag_en", models.CharField(max_length=80, verbose_name="Тег (EN)")),
                ("meta_ru", models.CharField(max_length=120, verbose_name="Подзаголовок (RU)")),
                ("meta_en", models.CharField(max_length=120, verbose_name="Подзаголовок (EN)")),
                ("title_ru", models.CharField(max_length=200, verbose_name="Заголовок (RU)")),
                ("title_en", models.CharField(max_length=200, verbose_name="Заголовок (EN)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("primary_url", models.URLField(verbose_name="Основная ссылка")),
                ("secondary_url", models.URLField(blank=True, verbose_name="Дополнительная ссылка")),
                ("primary_label_ru", models.CharField(default="PDF", max_length=80, verbose_name="Текст основной ссылки (RU)")),
                ("primary_label_en", models.CharField(default="PDF", max_length=80, verbose_name="Текст основной ссылки (EN)")),
                ("secondary_label_ru", models.CharField(default="Google Slides", max_length=80, verbose_name="Текст доп. ссылки (RU)")),
                ("secondary_label_en", models.CharField(default="Google Slides", max_length=80, verbose_name="Текст доп. ссылки (EN)")),
            ],
            options={"verbose_name": "Презентация", "verbose_name_plural": "Презентации", "ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Project",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("tag_ru", models.CharField(max_length=80, verbose_name="Тег (RU)")),
                ("tag_en", models.CharField(max_length=80, verbose_name="Тег (EN)")),
                ("meta_ru", models.CharField(max_length=120, verbose_name="Подзаголовок (RU)")),
                ("meta_en", models.CharField(max_length=120, verbose_name="Подзаголовок (EN)")),
                ("title_ru", models.CharField(max_length=200, verbose_name="Заголовок (RU)")),
                ("title_en", models.CharField(max_length=200, verbose_name="Заголовок (EN)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("github_url", models.URLField(verbose_name="GitHub URL")),
                ("details_url", models.URLField(blank=True, verbose_name="URL Подробнее")),
            ],
            options={"verbose_name": "Проект", "verbose_name_plural": "Проекты", "ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="ResearchWork",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("tag_ru", models.CharField(max_length=80, verbose_name="Тег (RU)")),
                ("tag_en", models.CharField(max_length=80, verbose_name="Тег (EN)")),
                ("meta_ru", models.CharField(max_length=120, verbose_name="Подзаголовок (RU)")),
                ("meta_en", models.CharField(max_length=120, verbose_name="Подзаголовок (EN)")),
                ("title_ru", models.CharField(max_length=200, verbose_name="Заголовок (RU)")),
                ("title_en", models.CharField(max_length=200, verbose_name="Заголовок (EN)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("primary_url", models.URLField(verbose_name="Основная ссылка")),
                ("secondary_url", models.URLField(blank=True, verbose_name="Дополнительная ссылка")),
                ("primary_label_ru", models.CharField(default="PDF", max_length=80, verbose_name="Текст основной ссылки (RU)")),
                ("primary_label_en", models.CharField(default="PDF", max_length=80, verbose_name="Текст основной ссылки (EN)")),
                ("secondary_label_ru", models.CharField(default="Подробнее", max_length=80, verbose_name="Текст доп. ссылки (RU)")),
                ("secondary_label_en", models.CharField(default="Read more", max_length=80, verbose_name="Текст доп. ссылки (EN)")),
            ],
            options={"verbose_name": "Исследовательская работа", "verbose_name_plural": "Исследовательские работы", "ordering": ["sort_order", "-created_at"]},
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("is_published", models.BooleanField(default=True, verbose_name="Опубликовано")),
                ("sort_order", models.PositiveIntegerField(default=100, verbose_name="Порядок")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Создано")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Обновлено")),
                ("tag_ru", models.CharField(max_length=80, verbose_name="Тег (RU)")),
                ("tag_en", models.CharField(max_length=80, verbose_name="Тег (EN)")),
                ("meta_ru", models.CharField(max_length=120, verbose_name="Подзаголовок (RU)")),
                ("meta_en", models.CharField(max_length=120, verbose_name="Подзаголовок (EN)")),
                ("title_ru", models.CharField(max_length=200, verbose_name="Заголовок (RU)")),
                ("title_en", models.CharField(max_length=200, verbose_name="Заголовок (EN)")),
                ("description_ru", models.TextField(verbose_name="Описание (RU)")),
                ("description_en", models.TextField(verbose_name="Описание (EN)")),
                ("embed_url", models.URLField(verbose_name="YouTube embed URL")),
                ("external_url", models.URLField(blank=True, verbose_name="Внешняя ссылка")),
                ("external_label_ru", models.CharField(default="Смотреть на YouTube", max_length=80, verbose_name="Текст внешней ссылки (RU)")),
                ("external_label_en", models.CharField(default="Watch on YouTube", max_length=80, verbose_name="Текст внешней ссылки (EN)")),
            ],
            options={"verbose_name": "Видео", "verbose_name_plural": "Видео", "ordering": ["sort_order", "-created_at"]},
        ),
    ]
